language: php

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - dnsutils
      - libpcap-dev

php:
  - '7.4'
  - nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

install:
  - composer install

script:
  - ./vendor/bin/phpstan analyse -n -vvv --ansi --level=max src
  - ./vendor/bin/psalm --show-info=true
  - ./vendor/bin/phpunit --coverage-text --debug
