name: Test Suite
on: [push, pull_request]
jobs:
  test-ubuntu-focal-fossa:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install libpcap
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev
    - name: Install dependencies
      run: composer install --no-scripts --no-suggest --no-interaction --prefer-dist --optimize-autoloader
    - name: PHPStan
      run: php -d memory_limit=-1 ./vendor/bin/phpstan analyse -n -vvv --ansi --level=max src
    - name: Psalm
      run: php -d memory_limit=-1 ./vendor/bin/psalm --show-info=true
    - name: PHPUnit
      run: sudo LIBPCAP_NAME=libpcap.so.0.8 php -d memory_limit=-1 ./vendor/bin/phpunit --debug
